Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
      - 'db/migrate/*'
      - 'db/schema.rb'
      - 'spec/**/*'